### ISSUE TITLE
Todo keyboard

### ISSUE THREAD

**Issue by oledid** [oledid/personal-settings#1]
These should be implemented cross platform:

- [x] `SHIFT + (key to the left of backspace)` should create a "finished" backtick on macOS
- [x] `SHIFT + (key to the left of backspace)` should create a "finished" backtick on Windows
- [x] `ALT + S` should save on Windows
- [x] `CTRL + LEFT / RIGHT` should move cursor one word left/right
- [x] `ALT + LEFT / RIGHT` should move cursor to start/end of current line on Windows
- [x] `RIGHT ALT GR + 7` should create `{` on macOS
- [x] `LEFT ALT GR + 0` should create `}` on macOS
- [x] `SHIFT + WIN + 8` should create `{` on Windows
- [x] `SHIFT + WIN + 9` should create `}` on Windows
- [x] The same style as above for `[` and `]` on macOS
- [x] The same style as above for `[` and `]` on Windows
- [x] `HOME` should move cursor to start of current line, and select text if `SHIFT` is pressed
- [x] `END` should move cursor to end of current line, and select text if `SHIFT` is pressed
